export const errorCodes = {
    ER_BAD_DB_ERROR: "BAD_DB_ERROR",
    ER_BAD_TABLE_ERROR: "BAD_TABLE_ERROR",
    NO_SUCH_TABLE: "NO_SUCH_TABLE_ERROR",
    ER_ACCESS_DENIED_ERROR: "ACCESS_DENIED_ERROR",
    ER_BAD_HOST_ERROR: "BAD_HOST_REQUEST",
};
