name: Build Ghost

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: authentication
        name: Setup Google Cloud Authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Create image name
        run: |
          echo "IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}-ghost:$(git rev-parse --short HEAD)" \
            >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . --file ./Dockerfile --tag $IMAGE_NAME

      - name: Authenticate Docker
        run: gcloud auth configure-docker --quiet

      - name: Push image to Google Cloud Container Registry
        run: docker push $IMAGE_NAME
