name: Tests

on:
  workflow_dispatch: {}
  push:
    paths:
      - "package.json"
      - "packages/**/source/**.ts"
      - "packages/**/source/**.tsx"
      - "package/**/test/**.ts"
      - "packages/**/source/**.jsx"
      - "packages/**/package.json"
      - "packages/**/tsconfig.json"
      - ".github/workflows/**/*.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Execute tests
        run: yarn test
